### PR TITLE
libxcb-randr support

### PR DESCRIPTION
**Pull request by nmschulte**
This is a work in progress; I'm mainly creating the PR to show progress to those that are interested.

There is still much to be done, but I think I've got a good grasp of the task at hand now and things should start flowing.

I will be actively re-writing this branch as I make changes and assimilate them into the history.  If you wish to collaborate, let me know and I will change my process to make this easier.

### CODE REVIEW

**Comment by nmschulte** [comment]
@phillipberndt Could you clarify:

You're using the same XID for the CRTC and the Mode in the OutputInfo structure; is that intentional?  https://github.com/phillipberndt/fakexrandr/blob/master/libXrandr.c#L126

**Comment by phillipberndt** [comment]
It should not matter, because there is no API that takes an arbitrary XID and then differentiates between CRTCs and modes. Each call takes either one or the other as an argument, so there's no ambiguity. BTW, neither the fake CRTC nor the fake mode are actual XIDs. They are just made up numbers.

**Comment by nmschulte** [comment]
That's what I was thinking; thanks.

**Comment by nmschulte** [comment]
I haven't had much time to work on this since I started this effort back in August; I've been making due with autorandr and hooks to configure my i3 config (which supports "fake-outputs" configuration), and I'm just biding my time until Monitors are supported in stable builds of Xorg, which eliminates (my) need for this library.

If anyone wants to pick up this work again, or would like me to continue, I'll be happy to help or consider looking at this again.  I've pushed my work in progress (which is pretty raw; the latest commit is just my working tree) to my repository.

**Comment by atmalik** [comment]
> If anyone wants to pick up this work again, or would like me to continue, I'll be happy to help or consider looking at this again.

it would be great to use this with KDE. :)

**Comment by phillipberndt** [comment]
@atmalik If you feel up to it yourself, go ahead and give it a try! I'll happily assist you with any questions that might arise along the way, it's not actually that hard if you regard the task as writing a proxy for a networking application and forget that it's actually about graphics ;-) My personal motivation for implementing this is quite low since the intel video drivers nowadays can correctly distinguish between the second and third monitor and people are slowly transitioning away from X11 anyway..

**Comment by tyll** [comment]
Just wondering, can the same that frakexrandr does be achieved with --setmonitor, see this answer:
https://askubuntu.com/a/998435

**Comment by phillipberndt** [comment]
Yes, that's basically what the monitors layer was invented for - making
hacks like this unnecessary :) Applications have to support it though, and
I don't know about the progress qt/gtk regarding that.

>

**Comment by 10110111** [comment]
I was trying to revive this development, but when I tried to compile your branch, I got lots of errors. The first one is this:
```
cc -O2 -fPIC -shared -o libxcb-randr.so libxcb-randr.c -ldl
libxcb-randr.c: In function ‘_config_foreach_split’:
libxcb-randr.c:78:60: error: ‘xcb_randr_output_info_t’ undeclared (first use in this function); did you mean ‘xcb_randr_output_next’?
   **fake_outputs = malloc(sizeof(struct FakeInfo) + sizeof(xcb_randr_output_info_t) + output_info->nameLen + sizeof("~NNN ") + sizeof(RRCrtc) + sizeof(RROutput) * output_info->nclone + (1 + output_info->nmode) * sizeof(RRMode));
                                                            ^~~~~~~~~~~~~~~~~~~~~~~
                                                            xcb_randr_output_next
```
This makes me wonder: what version of XRandR XCB were you using? Google fails to find _anything_ for `xcb_randr_output_info_t`. Or was it a type you were planning to define yourself?

**Comment by nmschulte** [comment]
I started making these changes before I knew the actual API, or knew which ones were synchronous and which weren't -- that type probably doesn't exist; I doubt the WIP actually builds, as you've discovered.

**Comment by 10110111** [comment]
I've made some progress in [my fork](https://github.com/10110111/fakexrandr). So far I've been able to make XFCE4-panel, XFWM4, Yakuake, KWin and KDE _Display and Monitor_ settings module believe the fakes. Haven't tested anything other yet.

**Pull request closed without merging**
